# Start with a rust alpine image
FROM rust:1-alpine3.15
# This is important, see https://github.com/rust-lang/docker-rust/issues/85
ENV RUSTFLAGS="-C target-feature=-crt-static"
# if needed, add additional dependencies here
RUN apk add --no-cache musl-dev openssl-dev
RUN cargo install --locked trunk
RUN rustup target add wasm32-unknown-unknown
# set the workdir and copy the source into it
WORKDIR /app
COPY ./frontend /frontend
COPY ./backend /app
COPY ./backend/data /app/data

WORKDIR /app
# do a release build
RUN cargo build --release


# use a plain alpine image, the alpine version needs to match the builder
FROM alpine:3.15
# if needed, install additional dependencies here
RUN apk add --no-cache libgcc
# copy the binary into the final image
COPY --from=0 /app/target/release/backend .
COPY --from=0 /app/data/ ./data
COPY --from=0 /app/dist/ ./dist

EXPOSE 8000
# set the binary as entrypoint
ENTRYPOINT ["/backend"]